language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
    - TESTBENCH_VERSION=3.0.*
    - TESTBENCH_VERSION=3.1.*
    - TESTBENCH_VERSION=3.2.*

matrix:
    exclude:
        - php: 5.4
          env: TESTBENCH_VERSION=3.1.*
        - php: 5.4
          env: TESTBENCH_VERSION=3.2.*

before_script:
  - composer self-update
  - composer require orchestra/testbench:${TESTBENCH_VERSION}
  - composer install --prefer-source --no-interaction --dev

script: phpunit
