language: php

php:
  - 5.5
  - 5.6
  - hhvm

env:
    - TESTBENCH_VERSION=3.1.*
    - TESTBENCH_VERSION=3.2.*

before_script:
  - composer self-update
  - composer require orchestra/testbench:${TESTBENCH_VERSION}
  - composer install --prefer-source --no-interaction --dev

script: phpunit